import { Job, RemoteType, ExperienceLevel, EmploymentType, JobSource } from '../modules/jobs/entities/job.entity';

export const jobsSeedData: Partial<Job>[] = [
  {
    external_id: 'seed-001',
    source: JobSource.DIRECT,
    title: 'Senior Full Stack Developer',
    company_name: 'TechCorp Solutions',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'San Francisco, CA, USA',
    city: 'San Francisco',
    state: 'California',
    country: 'USA',
    remote_type: RemoteType.HYBRID,
    salary_min: 120000,
    salary_max: 180000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `We are seeking an experienced Full Stack Developer to join our growing team. You will work on cutting-edge web applications using React, Node.js, and PostgreSQL.

Key Responsibilities:
- Design and develop scalable web applications
- Collaborate with cross-functional teams
- Mentor junior developers
- Participate in code reviews and technical discussions`,
    requirements: [
      '5+ years of experience in full-stack development',
      'Strong proficiency in React and Node.js',
      'Experience with PostgreSQL or similar databases',
      'Excellent problem-solving skills',
      'Strong communication skills',
    ],
    benefits: [
      'Competitive salary and equity',
      'Health, dental, and vision insurance',
      '401k matching',
      'Flexible work hours',
      'Professional development budget',
    ],
    skills: [
      'React',
      'Node.js',
      'TypeScript',
      'PostgreSQL',
      'Docker',
      'Kubernetes',
      'AWS',
      'GraphQL',
    ],
    experience_level: ExperienceLevel.SENIOR,
    experience_years_min: 5,
    experience_years_max: 10,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2 days ago
    expires_at: new Date(Date.now() + 28 * 24 * 60 * 60 * 1000), // 28 days from now
    application_url: 'https://techcorp.com/careers/apply/001',
    tags: ['featured', 'urgent'],
    is_active: true,
    is_featured: true,
    is_verified: true,
  },
  {
    external_id: 'seed-002',
    source: JobSource.DIRECT,
    title: 'Frontend Developer (React)',
    company_name: 'StartupXYZ',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'New York, NY, USA',
    city: 'New York',
    state: 'New York',
    country: 'USA',
    remote_type: RemoteType.REMOTE,
    salary_min: 90000,
    salary_max: 130000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `Join our dynamic startup as a Frontend Developer! We're building the next generation of SaaS products.

What you'll do:
- Build responsive and performant user interfaces
- Work closely with designers and backend developers
- Optimize application performance
- Write clean, maintainable code`,
    requirements: [
      '3+ years of React experience',
      'Strong understanding of JavaScript and CSS',
      'Experience with state management (Redux, Context API)',
      'Familiarity with testing frameworks (Jest, React Testing Library)',
    ],
    benefits: [
      'Stock options',
      'Remote-first culture',
      'Unlimited PTO',
      'Latest MacBook Pro',
      'Home office stipend',
    ],
    skills: [
      'React',
      'JavaScript',
      'TypeScript',
      'CSS',
      'HTML',
      'Redux',
      'Jest',
      'Git',
    ],
    experience_level: ExperienceLevel.MID,
    experience_years_min: 3,
    experience_years_max: 6,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5 days ago
    expires_at: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    application_url: 'https://startupxyz.com/jobs/frontend',
    tags: ['remote', 'startup'],
    is_active: true,
    is_featured: false,
    is_verified: true,
  },
  {
    external_id: 'seed-003',
    source: JobSource.DIRECT,
    title: 'DevOps Engineer',
    company_name: 'CloudNative Inc',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Austin, TX, USA',
    city: 'Austin',
    state: 'Texas',
    country: 'USA',
    remote_type: RemoteType.HYBRID,
    salary_min: 110000,
    salary_max: 160000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `We're looking for a skilled DevOps Engineer to help us build and maintain our cloud infrastructure.

Responsibilities:
- Manage AWS infrastructure using Terraform
- Build and maintain CI/CD pipelines
- Monitor system performance and reliability
- Implement security best practices`,
    requirements: [
      '4+ years of DevOps experience',
      'Strong knowledge of AWS services',
      'Experience with Terraform or similar IaC tools',
      'Proficiency in scripting (Python, Bash)',
      'Experience with containerization (Docker, Kubernetes)',
    ],
    benefits: [
      'Competitive compensation',
      'Comprehensive health coverage',
      'Flexible hybrid schedule',
      'Learning and development budget',
      'Gym membership',
    ],
    skills: [
      'AWS',
      'Terraform',
      'Docker',
      'Kubernetes',
      'Python',
      'Bash',
      'Jenkins',
      'GitLab CI',
      'Monitoring',
    ],
    experience_level: ExperienceLevel.SENIOR,
    experience_years_min: 4,
    experience_years_max: 8,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000), // 1 day ago
    expires_at: new Date(Date.now() + 29 * 24 * 60 * 60 * 1000),
    application_url: 'https://cloudnative.com/careers/devops',
    tags: ['cloud', 'infrastructure'],
    is_active: true,
    is_featured: true,
    is_verified: true,
  },
  {
    external_id: 'seed-004',
    source: JobSource.DIRECT,
    title: 'Junior Backend Developer',
    company_name: 'DataDriven Co',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Seattle, WA, USA',
    city: 'Seattle',
    state: 'Washington',
    country: 'USA',
    remote_type: RemoteType.ONSITE,
    salary_min: 70000,
    salary_max: 95000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `Great opportunity for a Junior Backend Developer to grow their career!

What we offer:
- Mentorship from senior developers
- Work on real production systems
- Learn best practices in software engineering
- Collaborative team environment`,
    requirements: [
      '1-2 years of backend development experience',
      'Knowledge of Python or Node.js',
      'Understanding of databases (SQL and NoSQL)',
      'Basic understanding of REST APIs',
      'Good problem-solving skills',
    ],
    benefits: [
      'Health insurance',
      'Professional development',
      'Mentorship program',
      'Team outings',
      'Snacks and beverages',
    ],
    skills: [
      'Python',
      'Node.js',
      'PostgreSQL',
      'MongoDB',
      'REST API',
      'Git',
      'Linux',
    ],
    experience_level: ExperienceLevel.JUNIOR,
    experience_years_min: 1,
    experience_years_max: 3,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    expires_at: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000),
    application_url: 'https://datadriven.com/apply/backend-junior',
    tags: ['entry-level', 'mentorship'],
    is_active: true,
    is_featured: false,
    is_verified: true,
  },
  {
    external_id: 'seed-005',
    source: JobSource.DIRECT,
    title: 'Machine Learning Engineer',
    company_name: 'AI Innovations Lab',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Boston, MA, USA',
    city: 'Boston',
    state: 'Massachusetts',
    country: 'USA',
    remote_type: RemoteType.REMOTE,
    salary_min: 140000,
    salary_max: 200000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `Join our AI research team to build cutting-edge machine learning models!

Your role:
- Develop and deploy ML models at scale
- Research new ML techniques and algorithms
- Collaborate with product teams
- Optimize model performance and efficiency`,
    requirements: [
      'MS or PhD in Computer Science or related field',
      '3+ years of ML engineering experience',
      'Strong Python and ML framework experience (TensorFlow, PyTorch)',
      'Experience with MLOps and model deployment',
      'Published research papers (preferred)',
    ],
    benefits: [
      'Top-tier compensation and equity',
      'Flexible remote work',
      'Conference attendance budget',
      'GPU workstation provided',
      'Research time allocation',
    ],
    skills: [
      'Python',
      'TensorFlow',
      'PyTorch',
      'Scikit-learn',
      'MLOps',
      'Docker',
      'Kubernetes',
      'AWS',
      'Deep Learning',
    ],
    experience_level: ExperienceLevel.SENIOR,
    experience_years_min: 3,
    experience_years_max: 10,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    expires_at: new Date(Date.now() + 26 * 24 * 60 * 60 * 1000),
    application_url: 'https://ailab.com/careers/ml-engineer',
    tags: ['ai', 'ml', 'research'],
    is_active: true,
    is_featured: true,
    is_verified: true,
  },
  {
    external_id: 'seed-006',
    source: JobSource.DIRECT,
    title: 'UI/UX Designer',
    company_name: 'DesignFirst Studio',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Los Angeles, CA, USA',
    city: 'Los Angeles',
    state: 'California',
    country: 'USA',
    remote_type: RemoteType.HYBRID,
    salary_min: 85000,
    salary_max: 120000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `We're seeking a talented UI/UX Designer to create beautiful and intuitive user experiences.

What you'll do:
- Design user interfaces for web and mobile applications
- Create wireframes, prototypes, and user flows
- Conduct user research and usability testing
- Collaborate with developers and product managers`,
    requirements: [
      '3+ years of UI/UX design experience',
      'Proficiency in Figma and Adobe Creative Suite',
      'Strong portfolio demonstrating design skills',
      'Understanding of user-centered design principles',
      'Experience with design systems',
    ],
    benefits: [
      'Creative environment',
      'Latest design tools and software',
      'Flexible schedule',
      'Design conferences',
      'Health benefits',
    ],
    skills: [
      'Figma',
      'Adobe XD',
      'Sketch',
      'Photoshop',
      'Illustrator',
      'User Research',
      'Prototyping',
      'Design Systems',
    ],
    experience_level: ExperienceLevel.MID,
    experience_years_min: 3,
    experience_years_max: 6,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    expires_at: new Date(Date.now() + 24 * 24 * 60 * 60 * 1000),
    application_url: 'https://designfirst.com/apply/uiux',
    tags: ['design', 'creative'],
    is_active: true,
    is_featured: false,
    is_verified: true,
  },
  {
    external_id: 'seed-007',
    source: JobSource.DIRECT,
    title: 'Product Manager',
    company_name: 'ProductVision Inc',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Chicago, IL, USA',
    city: 'Chicago',
    state: 'Illinois',
    country: 'USA',
    remote_type: RemoteType.HYBRID,
    salary_min: 130000,
    salary_max: 170000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `Looking for an experienced Product Manager to drive our product strategy and roadmap.

Responsibilities:
- Define product vision and strategy
- Work with engineering and design teams
- Gather and analyze customer feedback
- Manage product lifecycle from concept to launch`,
    requirements: [
      '5+ years of product management experience',
      'Strong analytical and communication skills',
      'Experience with Agile methodologies',
      'Technical background preferred',
      'Track record of successful product launches',
    ],
    benefits: [
      'Executive compensation package',
      'Stock options',
      'Flexible work arrangement',
      'Professional development',
      'Team retreats',
    ],
    skills: [
      'Product Management',
      'Agile',
      'Scrum',
      'Data Analysis',
      'SQL',
      'Jira',
      'Roadmapping',
      'Stakeholder Management',
    ],
    experience_level: ExperienceLevel.SENIOR,
    experience_years_min: 5,
    experience_years_max: 10,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    expires_at: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000),
    application_url: 'https://productvision.com/careers/pm',
    tags: ['product', 'management'],
    is_active: true,
    is_featured: false,
    is_verified: true,
  },
  {
    external_id: 'seed-008',
    source: JobSource.DIRECT,
    title: 'Data Scientist',
    company_name: 'Analytics Pro',
    company_logo_url: 'https://via.placeholder.com/100',
    location: 'Denver, CO, USA',
    city: 'Denver',
    state: 'Colorado',
    country: 'USA',
    remote_type: RemoteType.REMOTE,
    salary_min: 115000,
    salary_max: 155000,
    salary_currency: 'USD',
    salary_period: 'yearly',
    description: `We're hiring a Data Scientist to extract insights from large datasets and build predictive models.

Your mission:
- Analyze complex datasets
- Build statistical and ML models
- Create data visualizations
- Present findings to stakeholders`,
    requirements: [
      'MS or PhD in Statistics, Mathematics, or related field',
      '3+ years of data science experience',
      'Strong Python and R skills',
      'Experience with SQL and big data tools',
      'Excellent communication skills',
    ],
    benefits: [
      'Competitive salary',
      'Remote work flexibility',
      'Learning budget',
      'Health and wellness benefits',
      'Latest hardware and software',
    ],
    skills: [
      'Python',
      'R',
      'SQL',
      'Pandas',
      'NumPy',
      'Scikit-learn',
      'Tableau',
      'Spark',
      'Statistics',
    ],
    experience_level: ExperienceLevel.MID,
    experience_years_min: 3,
    experience_years_max: 7,
    employment_type: EmploymentType.FULL_TIME,
    posted_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    expires_at: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
    application_url: 'https://analyticspro.com/join/data-scientist',
    tags: ['data', 'analytics'],
    is_active: true,
    is_featured: false,
    is_verified: true,
  },
];
