version: 0.2

# AWS CodeBuild buildspec for ApplyForUs Platform
# Simplified: Build web app only for initial deployment

env:
  variables:
    DOCKER_BUILDKIT: "1"
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
      - echo "Building with IMAGE_TAG=$IMAGE_TAG"
      - export ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building web app..."
      - docker build -t $ECR_REGISTRY/applyai-web:$IMAGE_TAG -t $ECR_REGISTRY/applyai-web:latest -f apps/web/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-web:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-web:latest
      - echo "Web app built and pushed successfully!"

  post_build:
    commands:
      - echo "Build completed - Image tag $IMAGE_TAG"
      - echo "[{\"name\":\"web\",\"imageUri\":\"$ECR_REGISTRY/applyai-web:$IMAGE_TAG\"}]" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
