version: 0.2

# AWS CodeBuild buildspec for ApplyForUs Platform
# Builds all services for full stack deployment

env:
  variables:
    DOCKER_BUILDKIT: "1"
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}
      - echo "Building with IMAGE_TAG=$IMAGE_TAG"
      - export ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building all services..."

      # Build auth-service (priority - needed for registration)
      - echo "Building auth-service..."
      - docker build --no-cache -t $ECR_REGISTRY/applyai-auth-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-auth-service:latest -f services/auth-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-auth-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-auth-service:latest

      # Build user-service (priority - needed for registration)
      - echo "Building user-service..."
      - docker build -t $ECR_REGISTRY/applyai-user-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-user-service:latest -f services/user-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-user-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-user-service:latest

      # Build web app
      - echo "Building web app..."
      - docker build -t $ECR_REGISTRY/applyai-web:$IMAGE_TAG -t $ECR_REGISTRY/applyai-web:latest -f apps/web/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-web:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-web:latest

      # Build remaining services
      - echo "Building job-service..."
      - docker build -t $ECR_REGISTRY/applyai-job-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-job-service:latest -f services/job-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-job-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-job-service:latest

      - echo "Building resume-service..."
      - docker build -t $ECR_REGISTRY/applyai-resume-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-resume-service:latest -f services/resume-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-resume-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-resume-service:latest

      - echo "Building notification-service..."
      - docker build -t $ECR_REGISTRY/applyai-notification-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-notification-service:latest -f services/notification-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-notification-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-notification-service:latest

      - echo "Building analytics-service..."
      - docker build -t $ECR_REGISTRY/applyai-analytics-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-analytics-service:latest -f services/analytics-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-analytics-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-analytics-service:latest

      - echo "Building payment-service..."
      - docker build -t $ECR_REGISTRY/applyai-payment-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-payment-service:latest -f services/payment-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-payment-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-payment-service:latest

      - echo "Building orchestrator-service..."
      - docker build -t $ECR_REGISTRY/applyai-orchestrator-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-orchestrator-service:latest -f services/orchestrator-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-orchestrator-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-orchestrator-service:latest

      - echo "Building auto-apply-service..."
      - docker build -t $ECR_REGISTRY/applyai-auto-apply-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-auto-apply-service:latest -f services/auto-apply-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-auto-apply-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-auto-apply-service:latest

      - echo "Building ai-service..."
      - docker build -t $ECR_REGISTRY/applyai-ai-service:$IMAGE_TAG -t $ECR_REGISTRY/applyai-ai-service:latest -f services/ai-service/Dockerfile .
      - docker push $ECR_REGISTRY/applyai-ai-service:$IMAGE_TAG
      - docker push $ECR_REGISTRY/applyai-ai-service:latest

      - echo "All services built and pushed successfully!"

  post_build:
    commands:
      - echo "Build completed - Image tag $IMAGE_TAG"
      - |
        cat > imagedefinitions.json << EOF
        [
          {"name":"web","imageUri":"$ECR_REGISTRY/applyai-web:$IMAGE_TAG"},
          {"name":"auth","imageUri":"$ECR_REGISTRY/applyai-auth-service:$IMAGE_TAG"},
          {"name":"user","imageUri":"$ECR_REGISTRY/applyai-user-service:$IMAGE_TAG"},
          {"name":"job","imageUri":"$ECR_REGISTRY/applyai-job-service:$IMAGE_TAG"},
          {"name":"resume","imageUri":"$ECR_REGISTRY/applyai-resume-service:$IMAGE_TAG"},
          {"name":"notification","imageUri":"$ECR_REGISTRY/applyai-notification-service:$IMAGE_TAG"},
          {"name":"analytics","imageUri":"$ECR_REGISTRY/applyai-analytics-service:$IMAGE_TAG"},
          {"name":"payment","imageUri":"$ECR_REGISTRY/applyai-payment-service:$IMAGE_TAG"},
          {"name":"orchestrator","imageUri":"$ECR_REGISTRY/applyai-orchestrator-service:$IMAGE_TAG"},
          {"name":"auto-apply","imageUri":"$ECR_REGISTRY/applyai-auto-apply-service:$IMAGE_TAG"},
          {"name":"ai","imageUri":"$ECR_REGISTRY/applyai-ai-service:$IMAGE_TAG"}
        ]
        EOF

artifacts:
  files:
    - imagedefinitions.json
  discard-paths: yes
