# ============================================================================
# Pipeline Health Monitor - ApplyForUs Platform
# ============================================================================
# Scheduled pipeline to monitor CI/CD health and alert on issues
# Runs every 15 minutes to check pipeline status, AKS health, ACR images
# ============================================================================

trigger: none  # Manual or scheduled only

schedules:
  - cron: '*/15 * * * *'  # Every 15 minutes
    displayName: 'Pipeline Health Check'
    branches:
      include:
        - main
        - develop
    always: true

variables:
  - name: AZURE_SUBSCRIPTION
    value: 'ApplyPlatform'
  - name: ACR_NAME
    value: 'applyforusacr'
  - name: AKS_RESOURCE_GROUP
    value: 'applyforus-prod-rg'
  - name: AKS_CLUSTER_NAME
    value: 'applyforus-aks'
  - name: K8S_NAMESPACE
    value: 'applyforus'
  - name: UNIFIED_PIPELINE_ID
    value: '22'

pool:
  vmImage: 'ubuntu-latest'

stages:
  # ==========================================================================
  # Stage 1: Pipeline Health Check
  # ==========================================================================
  - stage: PipelineHealth
    displayName: 'Pipeline Health'
    jobs:
      - job: CheckPipelines
        displayName: 'Check Recent Pipeline Runs'
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: 'Check Pipeline Status'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "=============================================="
                echo "PIPELINE HEALTH CHECK - $(date -u +%Y-%m-%dT%H:%M:%SZ)"
                echo "=============================================="

                # Get recent builds
                echo ""
                echo "=== Recent Pipeline Runs ==="

                az pipelines runs list \
                  --org https://dev.azure.com/citadelcloudmanagement \
                  --project ApplyPlatform \
                  --top 10 \
                  --query "[].{ID:id,Pipeline:definition.name,Status:status,Result:result,Branch:sourceBranch,Queued:queueTime}" \
                  -o table || echo "Unable to fetch pipeline runs"

                # Check for failed builds
                FAILED_BUILDS=$(az pipelines runs list \
                  --org https://dev.azure.com/citadelcloudmanagement \
                  --project ApplyPlatform \
                  --top 20 \
                  --query "[?result=='failed'].id" \
                  -o tsv | wc -l)

                if [ "$FAILED_BUILDS" -gt 0 ]; then
                  echo ""
                  echo "##vso[task.logissue type=warning]Found $FAILED_BUILDS failed builds in last 20 runs"
                fi

                # Check for stuck builds
                STUCK_BUILDS=$(az pipelines runs list \
                  --org https://dev.azure.com/citadelcloudmanagement \
                  --project ApplyPlatform \
                  --top 10 \
                  --query "[?status=='inProgress' || status=='notStarted'].id" \
                  -o tsv | wc -l)

                echo ""
                echo "In-progress/Queued builds: $STUCK_BUILDS"
            continueOnError: true

  # ==========================================================================
  # Stage 2: AKS Cluster Health
  # ==========================================================================
  - stage: AKSHealth
    displayName: 'AKS Health'
    dependsOn: PipelineHealth
    condition: always()
    jobs:
      - job: CheckAKS
        displayName: 'Check AKS Cluster'
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: 'AKS Cluster Health'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "=== AKS Cluster Health ==="

                # Check cluster state
                CLUSTER_STATE=$(az aks show \
                  --resource-group $(AKS_RESOURCE_GROUP) \
                  --name $(AKS_CLUSTER_NAME) \
                  --query "powerState.code" -o tsv 2>/dev/null || echo "Unknown")

                echo "Cluster State: $CLUSTER_STATE"

                if [ "$CLUSTER_STATE" != "Running" ]; then
                  echo "##vso[task.logissue type=error]AKS cluster is not running! State: $CLUSTER_STATE"
                fi

                # Get node status
                az aks get-credentials \
                  --resource-group $(AKS_RESOURCE_GROUP) \
                  --name $(AKS_CLUSTER_NAME) \
                  --overwrite-existing

                echo ""
                echo "=== Node Status ==="
                kubectl get nodes

                # Check for NotReady nodes
                NOT_READY=$(kubectl get nodes --no-headers | grep -v "Ready" | wc -l)
                if [ "$NOT_READY" -gt 0 ]; then
                  echo "##vso[task.logissue type=error]$NOT_READY nodes are not ready!"
                fi

                echo ""
                echo "=== Pod Status ($(K8S_NAMESPACE)) ==="
                kubectl get pods -n $(K8S_NAMESPACE) --no-headers 2>/dev/null || echo "Namespace not found"

                # Check for failed pods
                FAILED_PODS=$(kubectl get pods -n $(K8S_NAMESPACE) --no-headers 2>/dev/null | grep -E "Error|CrashLoopBackOff|ImagePullBackOff" | wc -l)
                if [ "$FAILED_PODS" -gt 0 ]; then
                  echo "##vso[task.logissue type=warning]$FAILED_PODS pods are in failed state"
                  kubectl get pods -n $(K8S_NAMESPACE) | grep -E "Error|CrashLoopBackOff|ImagePullBackOff"
                fi

                echo ""
                echo "=== Deployment Rollout Status ==="
                for deploy in web auth-service user-service job-service resume-service; do
                  STATUS=$(kubectl rollout status deployment/$deploy -n $(K8S_NAMESPACE) --timeout=5s 2>&1 || echo "Not found")
                  echo "$deploy: $STATUS"
                done
            continueOnError: true

  # ==========================================================================
  # Stage 3: ACR Image Health
  # ==========================================================================
  - stage: ACRHealth
    displayName: 'ACR Health'
    dependsOn: AKSHealth
    condition: always()
    jobs:
      - job: CheckACR
        displayName: 'Check Container Registry'
        steps:
          - checkout: none

          - task: AzureCLI@2
            displayName: 'ACR Repository Check'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "=== ACR Repository Status ==="

                # List repositories
                az acr repository list --name $(ACR_NAME) -o table

                echo ""
                echo "=== Latest Image Tags ==="

                SERVICES="applyai-web applyai-auth-service applyai-user-service applyai-job-service applyai-resume-service applyai-notification-service applyai-auto-apply-service applyai-analytics-service applyai-ai-service applyai-orchestrator-service"

                for service in $SERVICES; do
                  echo ""
                  echo ">>> $service"
                  az acr repository show-tags --name $(ACR_NAME) --repository $service --top 3 --orderby time_desc -o tsv 2>/dev/null || echo "  No tags found"
                done

                echo ""
                echo "=== ACR Health ==="
                az acr show --name $(ACR_NAME) --query "{name:name,status:status,adminUserEnabled:adminUserEnabled}" -o table
            continueOnError: true

  # ==========================================================================
  # Stage 4: Manifest Drift Detection
  # ==========================================================================
  - stage: DriftDetection
    displayName: 'Drift Detection'
    dependsOn: ACRHealth
    condition: always()
    jobs:
      - job: DetectDrift
        displayName: 'Detect Manifest Drift'
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Compare Deployed vs Repo'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "=== Manifest Drift Detection ==="

                az aks get-credentials \
                  --resource-group $(AKS_RESOURCE_GROUP) \
                  --name $(AKS_CLUSTER_NAME) \
                  --overwrite-existing

                echo ""
                echo "=== Comparing Deployed Images vs Latest Tags ==="

                DRIFTED=""

                SERVICES="web auth-service user-service job-service resume-service"

                for service in $SERVICES; do
                  # Get currently deployed image
                  DEPLOYED_IMAGE=$(kubectl get deployment $service -n $(K8S_NAMESPACE) -o jsonpath='{.spec.template.spec.containers[0].image}' 2>/dev/null || echo "not-deployed")

                  # Get latest ACR tag
                  LATEST_TAG=$(az acr repository show-tags --name $(ACR_NAME) --repository applyai-$service --top 1 --orderby time_desc -o tsv 2>/dev/null || echo "no-tags")

                  echo "$service:"
                  echo "  Deployed: $DEPLOYED_IMAGE"
                  echo "  Latest:   $(ACR_NAME).azurecr.io/applyai-$service:$LATEST_TAG"

                  if [ "$DEPLOYED_IMAGE" != "$(ACR_NAME).azurecr.io/applyai-$service:$LATEST_TAG" ] && [ "$LATEST_TAG" != "latest" ]; then
                    echo "  STATUS: DRIFT DETECTED"
                    DRIFTED="$DRIFTED $service"
                  else
                    echo "  STATUS: OK"
                  fi
                  echo ""
                done

                if [ -n "$DRIFTED" ]; then
                  echo "##vso[task.logissue type=warning]Drift detected in:$DRIFTED"
                fi
            continueOnError: true

  # ==========================================================================
  # Stage 5: Health Summary
  # ==========================================================================
  - stage: Summary
    displayName: 'Health Summary'
    dependsOn:
      - PipelineHealth
      - AKSHealth
      - ACRHealth
      - DriftDetection
    condition: always()
    jobs:
      - job: GenerateSummary
        displayName: 'Generate Health Summary'
        steps:
          - script: |
              echo "=============================================="
              echo "       APPLYFORUD MONITORING SUMMARY"
              echo "=============================================="
              echo ""
              echo "Check Time: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
              echo ""
              echo "Stages Checked:"
              echo "  1. Pipeline Health     - Checked"
              echo "  2. AKS Cluster Health  - Checked"
              echo "  3. ACR Registry        - Checked"
              echo "  4. Manifest Drift      - Checked"
              echo ""
              echo "=============================================="
              echo "Next check in 15 minutes"
              echo "=============================================="
            displayName: 'Print Summary'
