"""Schemas package for AI Service."""

from .request_schemas import (
    ResumeParseRequest,
    ResumeOptimizeRequest,
    ATSScoreRequest,
    GenerateSectionRequest,
    EnhanceResumeRequest,
    MatchJobsRequest,
    MatchCandidatesRequest,
    MatchScoreRequest,
    SalaryPredictRequest,
    SuccessPredictRequest,
    TimeToHirePredictRequest,
    CandidateProfile,
    JobPosting,
    Resume,
)
from .response_schemas import (
    ParsedResume,
    OptimizedResume,
    ATSScore,
    GeneratedSection,
    EnhancedResume,
    MatchScore,
    JobMatch,
    CandidateMatch,
    MatchJobsResponse,
    MatchCandidatesResponse,
    MatchExplanation,
    SalaryPrediction,
    SuccessPrediction,
    TimeToHirePrediction,
    ErrorResponse,
    HealthResponse,
    Keyword,
    BiasReport,
    AuditResult,
)

__all__ = [
    # Request schemas
    "ResumeParseRequest",
    "ResumeOptimizeRequest",
    "ATSScoreRequest",
    "GenerateSectionRequest",
    "EnhanceResumeRequest",
    "MatchJobsRequest",
    "MatchCandidatesRequest",
    "MatchScoreRequest",
    "SalaryPredictRequest",
    "SuccessPredictRequest",
    "TimeToHirePredictRequest",
    "CandidateProfile",
    "JobPosting",
    "Resume",
    # Response schemas
    "ParsedResume",
    "OptimizedResume",
    "ATSScore",
    "GeneratedSection",
    "EnhancedResume",
    "MatchScore",
    "JobMatch",
    "CandidateMatch",
    "MatchJobsResponse",
    "MatchCandidatesResponse",
    "MatchExplanation",
    "SalaryPrediction",
    "SuccessPrediction",
    "TimeToHirePrediction",
    "ErrorResponse",
    "HealthResponse",
    "Keyword",
    "BiasReport",
    "AuditResult",
]
