name: Secret Rotation

on:
  schedule:
    - cron: '0 3 1 * *'  # Monthly on 1st at 3 AM
  workflow_dispatch:
    inputs:
      secret_type:
        description: 'Type of secrets to rotate'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - database
          - api_keys
          - jwt
          - certificates
      environment:
        description: 'Environment'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - dev
          - staging
          - prod
      dry_run:
        description: 'Dry run (do not actually rotate)'
        required: false
        type: boolean
        default: true

env:
  KEY_VAULT_NAME: applyforus-kv

jobs:
  prepare:
    name: Prepare Rotation
    runs-on: ubuntu-latest
    outputs:
      rotation_id: ${{ steps.id.outputs.rotation_id }}
      environments: ${{ steps.envs.outputs.environments }}
    steps:
      - name: Generate rotation ID
        id: id
        run: |
          ROTATION_ID="rot-$(date +%Y%m%d%H%M%S)-${{ github.run_number }}"
          echo "rotation_id=$ROTATION_ID" >> $GITHUB_OUTPUT
          echo "Rotation ID: $ROTATION_ID"

      - name: Determine environments
        id: envs
        run: |
          if [ "${{ github.event.inputs.environment }}" = "all" ] || [ -z "${{ github.event.inputs.environment }}" ]; then
            echo 'environments=["dev", "staging", "prod"]' >> $GITHUB_OUTPUT
          else
            echo 'environments=["${{ github.event.inputs.environment }}"]' >> $GITHUB_OUTPUT
          fi

  backup-secrets:
    name: Backup Current Secrets
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Backup secrets metadata
        run: |
          echo "Creating secret backup manifest..."
          mkdir -p backup

          # List all secrets (names only, not values)
          az keyvault secret list \
            --vault-name ${{ env.KEY_VAULT_NAME }} \
            --query "[].{name:name, enabled:attributes.enabled, expires:attributes.expires}" \
            -o json > backup/secrets-manifest-${{ needs.prepare.outputs.rotation_id }}.json

          echo "Backup manifest created"
          cat backup/secrets-manifest-${{ needs.prepare.outputs.rotation_id }}.json

      - name: Upload backup manifest
        uses: actions/upload-artifact@v4
        with:
          name: secrets-backup-${{ needs.prepare.outputs.rotation_id }}
          path: backup/
          retention-days: 90

  rotate-database-passwords:
    name: Rotate Database Passwords
    runs-on: ubuntu-latest
    needs: [prepare, backup-secrets]
    if: github.event.inputs.secret_type == 'all' || github.event.inputs.secret_type == 'database' || github.event.inputs.secret_type == ''
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.prepare.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate new password
        id: newpass
        run: |
          # Generate a strong password
          NEW_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9!@#$%' | head -c 32)
          echo "::add-mask::$NEW_PASSWORD"
          echo "password=$NEW_PASSWORD" >> $GITHUB_OUTPUT

      - name: Rotate database password
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "Rotating database password for ${{ matrix.environment }}..."

          # Update in Azure Key Vault
          az keyvault secret set \
            --vault-name ${{ env.KEY_VAULT_NAME }} \
            --name "sql-admin-password-${{ matrix.environment }}" \
            --value "${{ steps.newpass.outputs.password }}" \
            --tags environment=${{ matrix.environment }} rotated=$(date +%Y-%m-%d) rotation_id=${{ needs.prepare.outputs.rotation_id }}

          # Update Azure SQL Server password
          # Note: This requires the appropriate permissions
          # az sql server update --name applyforus-${{ matrix.environment }}-sql \
          #   --resource-group applyforus-${{ matrix.environment }}-rg \
          #   --admin-password "${{ steps.newpass.outputs.password }}"

          echo "Database password rotated for ${{ matrix.environment }}"

      - name: Dry run output
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "DRY RUN: Would rotate database password for ${{ matrix.environment }}"
          echo "New password would be stored in Key Vault as sql-admin-password-${{ matrix.environment }}"

  rotate-jwt-secrets:
    name: Rotate JWT Secrets
    runs-on: ubuntu-latest
    needs: [prepare, backup-secrets]
    if: github.event.inputs.secret_type == 'all' || github.event.inputs.secret_type == 'jwt' || github.event.inputs.secret_type == ''
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Generate new JWT secrets
        id: jwt
        run: |
          JWT_SECRET=$(openssl rand -hex 64)
          JWT_REFRESH_SECRET=$(openssl rand -hex 64)
          echo "::add-mask::$JWT_SECRET"
          echo "::add-mask::$JWT_REFRESH_SECRET"
          echo "jwt_secret=$JWT_SECRET" >> $GITHUB_OUTPUT
          echo "jwt_refresh_secret=$JWT_REFRESH_SECRET" >> $GITHUB_OUTPUT

      - name: Rotate JWT secrets
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "Rotating JWT secrets..."

          az keyvault secret set \
            --vault-name ${{ env.KEY_VAULT_NAME }} \
            --name "jwt-secret" \
            --value "${{ steps.jwt.outputs.jwt_secret }}" \
            --tags rotated=$(date +%Y-%m-%d) rotation_id=${{ needs.prepare.outputs.rotation_id }}

          az keyvault secret set \
            --vault-name ${{ env.KEY_VAULT_NAME }} \
            --name "jwt-refresh-secret" \
            --value "${{ steps.jwt.outputs.jwt_refresh_secret }}" \
            --tags rotated=$(date +%Y-%m-%d) rotation_id=${{ needs.prepare.outputs.rotation_id }}

          echo "JWT secrets rotated"

      - name: Dry run output
        if: github.event.inputs.dry_run == 'true'
        run: |
          echo "DRY RUN: Would rotate JWT secrets"

  rotate-api-keys:
    name: Rotate API Keys
    runs-on: ubuntu-latest
    needs: [prepare, backup-secrets]
    if: github.event.inputs.secret_type == 'all' || github.event.inputs.secret_type == 'api_keys' || github.event.inputs.secret_type == ''
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check API key expiration
        run: |
          echo "Checking API key expiration dates..."

          # List secrets with expiration
          az keyvault secret list \
            --vault-name ${{ env.KEY_VAULT_NAME }} \
            --query "[?contains(name, 'api-key')].{name:name, expires:attributes.expires}" \
            -o table

      - name: Rotate SendGrid API key
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "Note: SendGrid API key rotation requires manual regeneration in SendGrid dashboard"
          echo "Please update the key in Azure Key Vault after regenerating in SendGrid"

      - name: Rotate Stripe keys
        if: github.event.inputs.dry_run != 'true'
        run: |
          echo "Note: Stripe keys should be rotated via Stripe Dashboard"
          echo "For test environments, consider using rotating API keys feature"

      - name: Document rotation requirements
        run: |
          echo "## API Key Rotation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Service | Action Required |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|-----------------|" >> $GITHUB_STEP_SUMMARY
          echo "| SendGrid | Manual rotation in dashboard |" >> $GITHUB_STEP_SUMMARY
          echo "| Stripe | Rotate via Stripe Dashboard |" >> $GITHUB_STEP_SUMMARY
          echo "| OpenAI | Manual rotation in platform |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "*After rotating, update secrets in Azure Key Vault*" >> $GITHUB_STEP_SUMMARY

  sync-to-kubernetes:
    name: Sync Secrets to Kubernetes
    runs-on: ubuntu-latest
    needs: [prepare, rotate-database-passwords, rotate-jwt-secrets]
    if: always() && github.event.inputs.dry_run != 'true' && (needs.rotate-database-passwords.result == 'success' || needs.rotate-jwt-secrets.result == 'success')
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: applyforus-${{ matrix.environment }}-rg
          cluster-name: applyforus-${{ matrix.environment }}-aks
        continue-on-error: true

      - name: Sync secrets to Kubernetes
        run: |
          NAMESPACE="applyforus"
          if [ "${{ matrix.environment }}" != "prod" ]; then
            NAMESPACE="applyforus-${{ matrix.environment }}"
          fi

          echo "Syncing secrets to $NAMESPACE namespace..."

          # Fetch secrets from Key Vault
          JWT_SECRET=$(az keyvault secret show --vault-name ${{ env.KEY_VAULT_NAME }} --name jwt-secret --query value -o tsv)
          DB_PASSWORD=$(az keyvault secret show --vault-name ${{ env.KEY_VAULT_NAME }} --name sql-admin-password-${{ matrix.environment }} --query value -o tsv 2>/dev/null || echo "")

          # Update Kubernetes secret
          if [ -n "$JWT_SECRET" ]; then
            kubectl create secret generic app-secrets \
              --from-literal=JWT_SECRET="$JWT_SECRET" \
              --namespace=$NAMESPACE \
              --dry-run=client -o yaml | kubectl apply -f -
          fi

          echo "Secrets synced to ${{ matrix.environment }}"
        continue-on-error: true

  restart-services:
    name: Restart Services
    runs-on: ubuntu-latest
    needs: [prepare, sync-to-kubernetes]
    if: always() && github.event.inputs.dry_run != 'true' && needs.sync-to-kubernetes.result == 'success'
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: applyforus-${{ matrix.environment }}-rg
          cluster-name: applyforus-${{ matrix.environment }}-aks
        continue-on-error: true

      - name: Rolling restart services
        run: |
          NAMESPACE="applyforus"
          if [ "${{ matrix.environment }}" != "prod" ]; then
            NAMESPACE="applyforus-${{ matrix.environment }}"
          fi

          echo "Performing rolling restart in $NAMESPACE..."

          # Restart deployments to pick up new secrets
          for deployment in auth-service user-service job-service; do
            kubectl rollout restart deployment/$deployment -n $NAMESPACE 2>/dev/null || true
          done

          # Wait for rollouts
          for deployment in auth-service user-service job-service; do
            kubectl rollout status deployment/$deployment -n $NAMESPACE --timeout=300s 2>/dev/null || true
          done

          echo "Services restarted in ${{ matrix.environment }}"
        continue-on-error: true

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [prepare, rotate-database-passwords, rotate-jwt-secrets, rotate-api-keys, sync-to-kubernetes, restart-services]
    if: always()
    steps:
      - name: Generate rotation report
        run: |
          echo "## Secret Rotation Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Rotation ID:** ${{ needs.prepare.outputs.rotation_id }}" >> $GITHUB_STEP_SUMMARY
          echo "**Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "**Dry Run:** ${{ github.event.inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Results" >> $GITHUB_STEP_SUMMARY
          echo "| Task | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Database Passwords | ${{ needs.rotate-database-passwords.result == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| JWT Secrets | ${{ needs.rotate-jwt-secrets.result == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| API Keys | ${{ needs.rotate-api-keys.result == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| K8s Sync | ${{ needs.sync-to-kubernetes.result == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Service Restart | ${{ needs.restart-services.result == 'success' && '✅' || '⚠️' }} |" >> $GITHUB_STEP_SUMMARY

      - name: Notify Slack
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "🔐 Secret Rotation ${{ github.event.inputs.dry_run == 'true' && '(Dry Run)' || 'Completed' }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Secret Rotation Report"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Rotation ID:*\n${{ needs.prepare.outputs.rotation_id }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Dry Run:*\n${{ github.event.inputs.dry_run == 'true' && 'Yes' || 'No' }}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Results:*\n• Database: ${{ needs.rotate-database-passwords.result }}\n• JWT: ${{ needs.rotate-jwt-secrets.result }}\n• K8s Sync: ${{ needs.sync-to-kubernetes.result }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
