"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOGGER_INSTANCE = exports.LOGGER_OPTIONS = exports.LoggingExceptionFilter = exports.LoggingInterceptor = exports.LoggingModule = exports.PerformanceTracker = exports.createUserContextMiddleware = exports.sanitizeLogData = exports.errorLoggingMiddleware = exports.responseTimeMiddleware = exports.correlationMiddleware = exports.requestLoggingMiddleware = exports.formatErrorLog = exports.formatRequestLog = exports.formatBytes = exports.formatDuration = exports.createRequestLogFormat = exports.isSensitiveField = exports.filterSensitiveData = exports.createStructuredFormat = exports.LoggingConfigValidator = exports.getEnvironmentSpecificConfig = exports.LOG_LEVEL_DESCRIPTIONS = exports.shouldLog = exports.getLogLevelPriority = exports.isProductionEnvironment = exports.getLogLevelFromEnvironment = exports.createLoggingConfig = exports.setupLoggingContext = exports.correlationIdMiddleware = exports.LoggerContext = exports.LogLevel = exports.Logger = void 0;
var logger_1 = require("./logger");
Object.defineProperty(exports, "Logger", { enumerable: true, get: function () { return logger_1.Logger; } });
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return logger_1.LogLevel; } });
var context_1 = require("./context");
Object.defineProperty(exports, "LoggerContext", { enumerable: true, get: function () { return context_1.LoggerContext; } });
Object.defineProperty(exports, "correlationIdMiddleware", { enumerable: true, get: function () { return context_1.correlationIdMiddleware; } });
Object.defineProperty(exports, "setupLoggingContext", { enumerable: true, get: function () { return context_1.setupLoggingContext; } });
var config_1 = require("./config");
Object.defineProperty(exports, "createLoggingConfig", { enumerable: true, get: function () { return config_1.createLoggingConfig; } });
Object.defineProperty(exports, "getLogLevelFromEnvironment", { enumerable: true, get: function () { return config_1.getLogLevelFromEnvironment; } });
Object.defineProperty(exports, "isProductionEnvironment", { enumerable: true, get: function () { return config_1.isProductionEnvironment; } });
Object.defineProperty(exports, "getLogLevelPriority", { enumerable: true, get: function () { return config_1.getLogLevelPriority; } });
Object.defineProperty(exports, "shouldLog", { enumerable: true, get: function () { return config_1.shouldLog; } });
Object.defineProperty(exports, "LOG_LEVEL_DESCRIPTIONS", { enumerable: true, get: function () { return config_1.LOG_LEVEL_DESCRIPTIONS; } });
Object.defineProperty(exports, "getEnvironmentSpecificConfig", { enumerable: true, get: function () { return config_1.getEnvironmentSpecificConfig; } });
Object.defineProperty(exports, "LoggingConfigValidator", { enumerable: true, get: function () { return config_1.LoggingConfigValidator; } });
var formats_1 = require("./formats");
Object.defineProperty(exports, "createStructuredFormat", { enumerable: true, get: function () { return formats_1.createStructuredFormat; } });
Object.defineProperty(exports, "filterSensitiveData", { enumerable: true, get: function () { return formats_1.filterSensitiveData; } });
Object.defineProperty(exports, "isSensitiveField", { enumerable: true, get: function () { return formats_1.isSensitiveField; } });
Object.defineProperty(exports, "createRequestLogFormat", { enumerable: true, get: function () { return formats_1.createRequestLogFormat; } });
Object.defineProperty(exports, "formatDuration", { enumerable: true, get: function () { return formats_1.formatDuration; } });
Object.defineProperty(exports, "formatBytes", { enumerable: true, get: function () { return formats_1.formatBytes; } });
Object.defineProperty(exports, "formatRequestLog", { enumerable: true, get: function () { return formats_1.formatRequestLog; } });
Object.defineProperty(exports, "formatErrorLog", { enumerable: true, get: function () { return formats_1.formatErrorLog; } });
var middleware_1 = require("./middleware");
Object.defineProperty(exports, "requestLoggingMiddleware", { enumerable: true, get: function () { return middleware_1.requestLoggingMiddleware; } });
Object.defineProperty(exports, "correlationMiddleware", { enumerable: true, get: function () { return middleware_1.correlationMiddleware; } });
Object.defineProperty(exports, "responseTimeMiddleware", { enumerable: true, get: function () { return middleware_1.responseTimeMiddleware; } });
Object.defineProperty(exports, "errorLoggingMiddleware", { enumerable: true, get: function () { return middleware_1.errorLoggingMiddleware; } });
Object.defineProperty(exports, "sanitizeLogData", { enumerable: true, get: function () { return middleware_1.sanitizeLogData; } });
Object.defineProperty(exports, "createUserContextMiddleware", { enumerable: true, get: function () { return middleware_1.createUserContextMiddleware; } });
Object.defineProperty(exports, "PerformanceTracker", { enumerable: true, get: function () { return middleware_1.PerformanceTracker; } });
var nestjs_module_1 = require("./nestjs.module");
Object.defineProperty(exports, "LoggingModule", { enumerable: true, get: function () { return nestjs_module_1.LoggingModule; } });
Object.defineProperty(exports, "LoggingInterceptor", { enumerable: true, get: function () { return nestjs_module_1.LoggingInterceptor; } });
Object.defineProperty(exports, "LoggingExceptionFilter", { enumerable: true, get: function () { return nestjs_module_1.LoggingExceptionFilter; } });
Object.defineProperty(exports, "LOGGER_OPTIONS", { enumerable: true, get: function () { return nestjs_module_1.LOGGER_OPTIONS; } });
Object.defineProperty(exports, "LOGGER_INSTANCE", { enumerable: true, get: function () { return nestjs_module_1.LOGGER_INSTANCE; } });
//# sourceMappingURL=index.js.map